name: pg-nocodb
services:
  nocodb:
    image: nocodb/nocodb:0.258.11
    container_name: pg-nocodb
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          memory: 512M
    ports:
      - target: 8080
        published: 10800
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data/app/data:/usr/app/data
    environment:
      NC_DB: "pg://postgres:5432?u=nocodb&p=nocodb&d=nocodb"
      NC_REDIS_URL: "redis://redis:6379/0"
    networks:
      - pg_nocodb
    x-casaos:
      envs:
        - container: NC_DB
          description:
            en_us: "Database URI"
        - container: NC_REDIS_URL
          description:
            en_us: "Redis URI"
      ports:
        - container: "10800"
          description:
            en_us: WebUI HTTP Port
networks:
  pg_nocodb:
    name: pg-nocodb
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: nocodb
  tagline:
    en_us: NocDB with PG and Redis.
  description:
    en_us: NocDB with PG and Redis!
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/nocodb/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/nocodb/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/nocodb/screenshot-3.png
  developer: nocodb.com
  author: Mobydack
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/nocodb/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/nocodb/icon.png
  category: WEB
  title:
    en_us: NocoDB (PG + Redis)
  port_map: '51821'